controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\TimerController::index

analysis:
    path: /analysis
    controller: App\Controller\AnalysisController::index

todo:
    path: /todo
    controller: App\Controller\TodoController::index